# Generated by Django 4.0.5 on 2022-07-01 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Titulo')),
                ('lastname', models.CharField(default='', max_length=50, verbose_name='Titulo')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Aurtores',
                'ordering': ('lastname',),
                'permissions': (('view_all_authors', 'Can view all authors'),),
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ('-id',),
                'permissions': (('view_all_categoties', 'Can view all categories'),),
            },
        ),
        migrations.CreateModel(
            name='Editors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Editorial')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'ordering': ('-id',),
                'permissions': (('view_all_editors', 'Can view all editors'),),
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Titulo')),
                ('subtitle', models.CharField(default='', max_length=50, verbose_name='Titulo')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('description', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Descripción')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='books/pictures', verbose_name='Imagen')),
                ('book_editor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='book_editor', to='books.editors', verbose_name='Editorial')),
                ('books_author', models.ManyToManyField(default='', related_name='books_author', to='books.authors', verbose_name='Autor(es)')),
                ('books_category', models.ManyToManyField(default='', related_name='tasks_category', to='books.categories', verbose_name='Categoria(s)')),
                ('books_register', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='book_editor', to=settings.AUTH_USER_MODEL, verbose_name='Editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ('title',),
                'permissions': (('view_all_books', 'Can view all books'),),
            },
        ),
    ]
