# Generated by Django 4.0.5 on 2022-07-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_authors_options_remove_authors_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='google_id',
            field=models.CharField(default='', max_length=20, verbose_name='Id Google'),
        ),
    ]
