# Generated by Django 4.0.5 on 2022-07-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='origen',
            field=models.CharField(default='db interna', max_length=20, verbose_name='Origen'),
        ),
    ]
