# Generated by Django 4.0.5 on 2022-07-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='google_id',
        ),
        migrations.AddField(
            model_name='books',
            name='external_id',
            field=models.CharField(default='', max_length=20, verbose_name='Id API externa'),
        ),
    ]
